### PR TITLE
Fix WIREMOCK_OPTIONS duplicated

### PR DESCRIPTION
**Pull request by jerosa**
## References

Bug: https://github.com/wiremock/wiremock-docker/issues/91

When passing the wiremock options sometimes fail. This is due the WIREMOCK_OPTIONS being duplicated. I've tested it in the entry point.sh adding -x for tracing.
```
❯ docker run -e WIREMOCK_OPTIONS='--container-threads=100 --verbose' wiremock/wiremock:test-opts
+ '[' '' = '' -o '' = - ']'
+ set -- java -cp '/var/wiremock/lib/*:/var/wiremock/extensions/*' wiremock.Run --container-threads=100 --verbose
+ '[' '' '!=' '' ']'
+ exec java -cp '/var/wiremock/lib/*:/var/wiremock/extensions/*' wiremock.Run --container-threads=100 --verbose --container-threads=100 --verbose
2023-10-20 09:25:02.700 Verbose logging enabled
Exception in thread "main" 
Exception: java.util.MissingResourceException thrown from the UncaughtExceptionHandler in thread "main"
```

## Submitter checklist

- [ ] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [ ] Recommended: If you participate in Hacktoberfest 2023, make sure you're [signed up](https://wiremock.org/events/hacktoberfest/) there and in the WireMock form 
- [ ] The PR request is well described and justified, including the body and the references
- [ ] The PR title represents the desired changelog entry
- [ ] The repository's code style is followed (see the contributing guide)
- [ ] Test coverage that demonstrates that the change works as expected
- [ ] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Comment by kapishmalik** [comment]
@jerosa u r reverting the change instead of fixing it.

**Comment by kapishmalik** [comment]
@jerosa  thanks for fixing this. You also need to fix in the file - https://github.com/wiremock/wiremock-docker/blob/main/alpine/docker-entrypoint.sh

**Comment by jerosa** [comment]
@kapishmalik solved also in that file

**Review by oleg-nenashev — APPROVED** [review]
Thanks! Indeed, it would lead to duplication

**Pull request merged**
