### PR TITLE
Update WireMock to 3.0.1 with bugfixes + Update Eclipse Temurin to 11.0.20_8

### PR DESCRIPTION
**Pull request by oleg-nenashev**
## References

- https://github.com/wiremock/wiremock/releases/tag/3.0.1

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Comment by bbezanson** [comment]
@oleg-nenashev before pulling in 3.0.1 would you consider updating the dockerfile to use the latest update for eclipse-temurin:11.0.20_8-jre?

**Comment by oleg-nenashev** [comment]
@bbezanson will do

**Comment by bbezanson** [comment]
@oleg-nenashev I decided to do the proper thing and instead of making you do the work I sent in a quick PR. I hope that helps better than just "telling/asking" :-)

**Comment by oleg-nenashev** [comment]
OK, merged both

**Pull request merged**
